// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPage_WebApp_Melton.Models;

#nullable disable

namespace MultiPage_WebApp_Melton.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20240124151151_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MultiPage_WebApp_Melton.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "123 Fake Street",
                            Name = "Bob",
                            Note = "Co-worker",
                            Number = 1234567890L
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "111 Maple Drive",
                            Name = "Sarah",
                            Note = "A",
                            Number = 987654321L
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "222 Sunset Lane",
                            Name = "Tom",
                            Note = "Tailor",
                            Number = 1032547698L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
